### ISSUE TITLE
App Icon doesn't change

### ISSUE THREAD

**Issue by btutal** [wal33d006/app_icon_changer#1]
Hi,
Thank you for creating this package and your medium post. I've completed all the steps and when I initiate function, I am getting a small popup that says "You have changed the icon for" with the small image of the original app icon but when I check app icon nothing changes. 

There is no output in Android Studio console but in XCode, I got this message below:
`2020-06-17 01:30:23.389839+0200 Runner[16060:3227218] [default] +[LSApplicationProxy applicationProxyFor*] is not a supported method for getting the LSApplicationProxy for the current process, use +[LSBundleProxy bundleProxyForCurrentProcess] instead.
App icon changed successfully.`

I am on the latest iOS and Flutter stable release. Do you have any idea what might be wrong? 
In addition, what is the best way to go back to the original icon? 

As far as I understand [from your post ](https://pub.dev/packages/app_icon_changer#-readme-tab-) There are 3 icons;  icon-white, icon-black, icon. The app has as a default 'icon' file set as an icon, right? 

In this setup, if I don't add 'icon' as an alternative as well, `AppIconChanger.changeIcon('icon');` doesn't work with message `App icon failed to due to The file doesn’t exist`

**Comment by wal33d006** [comment]
Have you setup the things that need to be done in the info.plist?
Also, did you try to clone and run the sample app?

**Comment by btutal** [comment]
Yes, sample app works fine. I've made the changes in info.plist as well. Only part that I am not sure is 
```
<key>CFBundlePrimaryIcon</key>
        <dict>
            <key>CFBundleIconFiles</key>
            <array>
                <string>icon</string>
            </array>
        </dict>
```

What should be  `icon` string?

**Comment by wal33d006** [comment]
You are missing Alternate icon key here. Check the info.plist file of the sample app here
example/ios/Runner/Info.plist

**Comment by btutal** [comment]
I have it. I have just pasted small part of the info.plist to ask about `icon` string. You don't have a icon@2x.png or something else in example project but for primary icon you are using `icon` why is that? 

I've added following snippet to my Info.plist
```
        <key>CFBundleIcons</key>
	<dict>
		<key>CFBundleAlternateIcons</key>
		<dict>
			<key>myapp</key>
			<dict>
				<key>UIPrerenderedIcon</key>
				<string>NO</string>
				<key>CFBundleIconFiles</key>
				<array>
					<string>myapp</string>
				</array>
			</dict>
			<key>myapp-original</key>
			<dict>
				<key>UIPrerenderedIcon</key>
				<string>NO</string>
				<key>CFBundleIconFiles</key>
				<array>
					<string>myapp-original</string>
				</array>
			</dict>
			<key>myapp-dark</key>
			<dict>
				<key>UIPrerenderedIcon</key>
				<string>NO</string>
				<key>CFBundleIconFiles</key>
				<array>
					<string>myapp-dark</string>
				</array>
			</dict>
		</dict>
		<key>CFBundlePrimaryIcon</key>
		<dict>
			<key>CFBundleIconFiles</key>
			<array>
				<string>myapp</string>
			</array>
		</dict>
		<key>UINewsstandIcon</key>
		<dict>
			<key>CFBundleIconFiles</key>
			<array>
				<string></string>
			</array>
			<key>UINewsstandBindingEdge</key>
			<string>UINewsstandBindingEdgeLeft</string>
			<key>UINewsstandBindingType</key>
			<string>UINewsstandBindingTypeMagazine</string>
		</dict>
	</dict>
```

**Comment by wal33d006** [comment]
Primary icon is the default icon which Flutter provides in the beginning. If you want your own default primary icon, set your icon the normal way first, and it will appear the first time. On a default, iOS picks up the icon through appIcon. You can change that through XCode or your can use flutter_launcher_icons package to change it

**Comment by btutal** [comment]
I've already configured that in the past. My problem is, it seems like package is changing the icon but it is always setting it to default one. In the popup that tells icon has changed, it is always showing the default app icon when the parameter is correct. When it is not correct, nothing happens as expected.

**Comment by wal33d006** [comment]
That’s weird if it’s working in the example and not in your code. Do you have @2x and @3x in your folder?

**Comment by btutal** [comment]
Yes, just to try it out, I've tried my icons in example app and it worked fine

**Comment by wal33d006** [comment]
That’s even weirder! For a safe side just compare the folder structure of your iOS with the example project, and your info.plist indentations

**Comment by btutal** [comment]
I've checked the complete setup from the beginning but couldn't find the problem. The log message below is written in the console every time and I see the popup of icon changed (always with original icon)
```
2020-06-18 01:22:16.549935+0200 Runner[19407:3807264] [default] +[LSApplicationProxy applicationProxyFor*] is not a supported method for getting the LSApplicationProxy for the current process, use +[LSBundleProxy bundleProxyForCurrentProcess] instead.
App icon changed successfully.
```

**Comment by wal33d006** [comment]
There must be something that is different in your project. Is your code shareable? Can u share it?

**Comment by btutal** [comment]
I have checked another package and had the same problem, apparently nothing wrong with this package. I will try to find out what's the problem but closing this issue now.

**Comment by nohli** [comment]
@btutal in case you still want this feature...and everyone else encountering the same problem:

When copying to Xcode, you can select 'create folder references' or 'create groups'...select groups and it works.

@wal33d006 maybe this would be good to add to the readme.

**Comment by wal33d006** [comment]
> @btutal in case you still want this feature...and everyone else encountering the same problem:
> 
> 
> 
> When copying to Xcode, you can select 'create folder references' or 'create groups'...select groups and it works.
> 
> 
> 
> @wal33d006 maybe this would be good to add in the readme.

@nohli Thanks, will add it there. Or maybe create a PR yourself ;)

**Comment by nohli** [comment]
Ok, I will do it :)

**Comment by wal33d006** [comment]
@nohli Thanks. This was the first time I got a PR from someone in the community! 🙌👨‍💻⚡️
